/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bob-h
 */
public class AdminRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminRegistrationJPanel
     */
    private Business business;
    private JPanel CardSequencePanel;
    private CardLayout inputAreaLayout;
    
    private static final String CARD_STUDENT = "Student";
    private static final String CARD_FACULTY = "Faculty";
    private static final String CARD_REGISTRAR = "Registrar";
    public AdminRegistrationJPanel(Business b, JPanel clp) {
        this.business = b;
        this.CardSequencePanel = clp;
        initComponents();
        
        setupInputArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        cmbFilter = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        InputArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student ", "Faculty", "Registrar" }));
        cmbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterActionPerformed(evt);
            }
        });

        btnBack.setText(">> Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(541, 541, 541))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(jPanel1);

        InputArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(InputArea);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout)CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        String selectedRole = (String) cmbFilter.getSelectedItem();
        
        if (selectedRole == null) {
            return;
        }
        
        switch (selectedRole) {
            case "Student":
                inputAreaLayout.show(InputArea, CARD_STUDENT);
                break;
            case "Faculty":
                inputAreaLayout.show(InputArea, CARD_FACULTY);
                break;
            case "Registrar":
                inputAreaLayout.show(InputArea, CARD_REGISTRAR);
                break;
            default:
                inputAreaLayout.show(InputArea, CARD_STUDENT);
                break;
        }
    }//GEN-LAST:event_cmbFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InputArea;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

private void setupInputArea() {
        inputAreaLayout = new CardLayout();
        InputArea.setLayout(inputAreaLayout);
        
        AdminStudentJPanel studentPanel = new AdminStudentJPanel(business, CardSequencePanel);
        AdminFacultyJPanel facultyPanel = new AdminFacultyJPanel(business, CardSequencePanel);
        
        JPanel registrarPanel = new JPanel();
        registrarPanel.add(new javax.swing.JLabel("Registrar Registration (Coming Soon)"));
        
        InputArea.add(studentPanel, CARD_STUDENT);
        InputArea.add(facultyPanel, CARD_FACULTY);
        InputArea.add(registrarPanel, CARD_REGISTRAR);
    }

}
