/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import Business.UserAccounts.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Profiles.RegistrarProfile;
import java.awt.CardLayout;

/**
 *
 * @author 心火牧神塞勒斯
 */
public class RegistrarProfileManagementJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount useraccount;
    javax.swing.JPanel CardSequencePanel;
    private RegistrarProfile currentRegistrarProfile;
    /**
     * Creates new form RegistrarProfileManagementJPanel
     */
    public RegistrarProfileManagementJPanel(Business b, JPanel clp, UserAccount ua) {
        this.business = b;
        this.CardSequencePanel = clp;
        this.useraccount = ua;
        this.currentRegistrarProfile = (RegistrarProfile) ua.getProfile();
        initComponents();
        loadProfileData();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblPhoneNumber = new javax.swing.JLabel();
        lblOfficeHour = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtOfficeHour = new javax.swing.JTextField();
        txtOfficeLocation = new javax.swing.JTextField();
        lblOfficeLocation = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPhoneNumber.setText("Phone Number");

        lblOfficeHour.setText("Office Hour");

        lblEmailAddress.setText("E-mail Address");

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });

        lblOfficeLocation.setText("Office Loaction");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEdit)
                        .addComponent(lblOfficeHour, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOfficeLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtOfficeHour, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOfficeLocation, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(0, 782, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(716, 716, 716))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailAddress)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNumber)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(lblOfficeHour))
                    .addComponent(txtOfficeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOfficeLocation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOfficeLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addContainerGap(335, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout)CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            // 1. 获取表单数据
            String officeHours = txtOfficeHour.getText().trim();
            String officeLocation = txtOfficeLocation.getText().trim();
            String phoneNumber = txtPhoneNumber.getText().trim();
            String emailAddress = txtEmailAddress.getText().trim();

            // 2. 数据验证
            if (officeHours.isEmpty()) {
                JOptionPane.showMessageDialog(this, "请输入办公时间", "错误", JOptionPane.ERROR_MESSAGE);
                txtOfficeHour.requestFocus();
                return;
            }

            if (officeLocation.isEmpty()) {
                JOptionPane.showMessageDialog(this, "请输入办公室位置", "错误", JOptionPane.ERROR_MESSAGE);
                txtOfficeLocation.requestFocus();
                return;
            }

            if (phoneNumber.isEmpty()) {
                JOptionPane.showMessageDialog(this, "请输入电话号码", "错误", JOptionPane.ERROR_MESSAGE);
                txtPhoneNumber.requestFocus();
                return;
            }

            if (emailAddress.isEmpty() || !emailAddress.contains("@")) {
                JOptionPane.showMessageDialog(this, "请输入有效的邮箱地址", "错误", JOptionPane.ERROR_MESSAGE);
                txtEmailAddress.requestFocus();
                return;
            }

            // 3. 更新RegistrarProfile信息
            currentRegistrarProfile.setOfficeHours(officeHours);
            currentRegistrarProfile.setOfficeLocation(officeLocation);
            currentRegistrarProfile.setPhone(phoneNumber);
            currentRegistrarProfile.setEmail(emailAddress);

            // 4. 显示成功和失败消息
            JOptionPane.showMessageDialog(this, 
                "个人信息更新成功！\n" +
                "办公时间: " + officeHours + "\n" +
                "办公室: " + officeLocation + "\n" +
                "电话: " + phoneNumber + "\n" +
                "邮箱: " + emailAddress, 
                "更新成功", 
                JOptionPane.INFORMATION_MESSAGE);
            setViewMode();
            } catch (Exception ex) {  
                JOptionPane.showMessageDialog(this, 
                    "保存失败: " + ex.getMessage(), 
                    "错误", 
                    JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblOfficeHour;
    private javax.swing.JLabel lblOfficeLocation;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtOfficeHour;
    private javax.swing.JTextField txtOfficeLocation;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables

    private void loadProfileData() {
        if (currentRegistrarProfile != null) {
            txtOfficeHour.setText(currentRegistrarProfile.getOfficeHours());
            txtOfficeLocation.setText(currentRegistrarProfile.getOfficeLocation());
            txtPhoneNumber.setText(currentRegistrarProfile.getPhone());
            txtEmailAddress.setText(currentRegistrarProfile.getEmail());
        }
    }

    private void setEditMode() {
        txtEmailAddress.setEnabled(true);
        txtPhoneNumber.setEnabled(true);
        txtOfficeHour.setEnabled(true);
        txtOfficeLocation.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSave.setEnabled(true);
    }

    private void setViewMode() {
        txtEmailAddress.setEnabled(false);
        txtPhoneNumber.setEnabled(false);
        txtOfficeHour.setEnabled(false);
        txtOfficeLocation.setEnabled(false);
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
    }
}
