/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

/**
 *
 * @author 心火牧神塞勒斯
 */
public class RegistrarWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarWorkAreaJPanel
     */
    public RegistrarWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseOfferingManagement = new javax.swing.JButton();
        btnProfileManagement = new javax.swing.JButton();
        btnReportingAnalytics = new javax.swing.JButton();
        btnStudentRegistration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTuition = new javax.swing.JButton();

        btnCourseOfferingManagement.setBackground(new java.awt.Color(102, 153, 255));
        btnCourseOfferingManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseOfferingManagement.setText("Course Offering Management");
        btnCourseOfferingManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseOfferingManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseOfferingManagement.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseOfferingManagement.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseOfferingManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseOfferingManagementIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnProfileManagement.setBackground(new java.awt.Color(102, 153, 255));
        btnProfileManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnProfileManagement.setText("Profile Management");
        btnProfileManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfileManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnProfileManagement.setMinimumSize(new java.awt.Dimension(20, 20));
        btnProfileManagement.setPreferredSize(new java.awt.Dimension(240, 25));
        btnProfileManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileManagementActionPerformed(evt);
            }
        });

        btnReportingAnalytics.setBackground(new java.awt.Color(102, 153, 255));
        btnReportingAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        btnReportingAnalytics.setText("Reporting & Analytics");
        btnReportingAnalytics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportingAnalytics.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReportingAnalytics.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReportingAnalytics.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReportingAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportingAnalyticsActionPerformed(evt);
            }
        });

        btnStudentRegistration.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentRegistration.setText("Student Registration");
        btnStudentRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStudentRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegistrationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Registrar Portal");

        btnTuition.setBackground(new java.awt.Color(102, 153, 255));
        btnTuition.setForeground(new java.awt.Color(255, 255, 255));
        btnTuition.setText("Tuition & Financial Reconciliation");
        btnTuition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTuition.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTuition.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTuition.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTuition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCourseOfferingManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnProfileManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStudentRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(btnReportingAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(581, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseOfferingManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportingAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseOfferingManagementIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseOfferingManagementIdentifyResourceAssetsActionPerformed
        StudentCourseworkManagementJPanel panel= new StudentCourseworkManagementJPanel(business,studentAccount,CardSequencePanel);
        CardSequencePanel.add("StudentCourseworkManagementJPanel",panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnCourseOfferingManagementIdentifyResourceAssetsActionPerformed

    private void btnProfileManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileManagementActionPerformed
        // TODO add your handling code here:
        StudentMangementDialog dialog = new StudentMangementDialog( (java.awt.Frame) SwingUtilities.getWindowAncestor(CardSequencePanel),true,business,studentAccount,useraccount);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnProfileManagementActionPerformed

    private void btnReportingAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportingAnalyticsActionPerformed
        // TODO add your handling code here:
        StudentGraduateDialog dialog = new StudentGraduateDialog( (java.awt.Frame) SwingUtilities.getWindowAncestor(CardSequencePanel),true,business,studentAccount);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnReportingAnalyticsActionPerformed

    private void btnStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegistrationActionPerformed
        // TODO add your handling code here:
        StudentCourseRegistrationJPanel panel= new StudentCourseRegistrationJPanel(business,studentAccount,CardSequencePanel);
        CardSequencePanel.add("StudentCourseRegistrationJPanel",panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnStudentRegistrationActionPerformed

    private void btnTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTuitionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseOfferingManagement;
    private javax.swing.JButton btnProfileManagement;
    private javax.swing.JButton btnReportingAnalytics;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JButton btnTuition;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
