/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import Business.UserAccounts.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author 心火牧神塞勒斯
 */
public class RegistrarWorkAreaJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount useraccount;
    javax.swing.JPanel CardSequencePanel;
    /**
     * Creates new form RegistrarWorkAreaJPanel
     */
    public RegistrarWorkAreaJPanel(Business b, JPanel clp, UserAccount ua) {
        this.business = b;
        this.CardSequencePanel = clp;
        this.useraccount = ua;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseManagement = new javax.swing.JButton();
        btnProfileManagement = new javax.swing.JButton();
        btnStudentRegistration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTuition = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnCourseManagement.setBackground(new java.awt.Color(102, 153, 255));
        btnCourseManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseManagement.setText("Course Offering Management");
        btnCourseManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseManagement.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseManagement.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseManagementIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnProfileManagement.setBackground(new java.awt.Color(102, 153, 255));
        btnProfileManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnProfileManagement.setText("Manage Own Profile");
        btnProfileManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfileManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnProfileManagement.setMinimumSize(new java.awt.Dimension(20, 20));
        btnProfileManagement.setPreferredSize(new java.awt.Dimension(240, 25));
        btnProfileManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileManagementActionPerformed(evt);
            }
        });

        btnStudentRegistration.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentRegistration.setText("Student Registration");
        btnStudentRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStudentRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegistrationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Registrar Portal");

        btnTuition.setBackground(new java.awt.Color(102, 153, 255));
        btnTuition.setForeground(new java.awt.Color(255, 255, 255));
        btnTuition.setText("Tuition & Financial Reconciliation");
        btnTuition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTuition.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTuition.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTuition.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(102, 153, 255));
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setText("Reporting & Analytics");
        btnReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReport.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReport.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReport.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTuition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCourseManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnProfileManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStudentRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(581, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseManagementIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseManagementIdentifyResourceAssetsActionPerformed
        RegistrarCourseManagementJPanel panel= new RegistrarCourseManagementJPanel(business,CardSequencePanel,useraccount);
        CardSequencePanel.add("RegistrarCourseManagementJPanel",panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);   
    }//GEN-LAST:event_btnCourseManagementIdentifyResourceAssetsActionPerformed

    private void btnProfileManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileManagementActionPerformed
        // TODO add your handling code here:
        RegistrarProfileManagementJPanel panel= new RegistrarProfileManagementJPanel(business,CardSequencePanel,useraccount);
        CardSequencePanel.add("RegistrarProfileManagementJPanel",panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);   
        
    }//GEN-LAST:event_btnProfileManagementActionPerformed

    private void btnStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegistrationActionPerformed
        // TODO add your handling code here:
        RegistrarStudentRegistrationJPanel panel= new RegistrarStudentRegistrationJPanel(business,CardSequencePanel,useraccount);
        CardSequencePanel.add("RegistrarStudentRegistrationJPanel",panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);  
    }//GEN-LAST:event_btnStudentRegistrationActionPerformed

    private void btnTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionActionPerformed
        // TODO add your handling code here:
        RegistrarTuitionJPanel panel= new RegistrarTuitionJPanel(business,CardSequencePanel,useraccount);
        CardSequencePanel.add("RegistrarTuitionJPanel",panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);          
    }//GEN-LAST:event_btnTuitionActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseManagement;
    private javax.swing.JButton btnProfileManagement;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JButton btnTuition;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
