/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Course.CourseGrade;
import Business.Person.Person;
import Business.Person.Student;
import Business.Profiles.StudentProfileDirectory;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class StudentGraduateDialog extends javax.swing.JDialog {

    private Business business;
    private StudentProfile studentAccount;
    private Student student;
 
    /**
     * Creates new form StudentRegisterDialog
     */
    public StudentGraduateDialog(java.awt.Frame parent, boolean modal,Business b,StudentProfile studentAccount) {
        super(parent, modal);
this.business = b;
this.studentAccount = studentAccount;
this.student = (Student) studentAccount.getStudent();

initComponents();

try {
        int earnedCredits = 0;
        boolean hasCore = false;

        StringBuilder transcriptText = new StringBuilder();

        for (CourseGrade cg : student.getTranscript()) {
            String courseId = cg.getCourse().getCourseId();
            String courseName = cg.getCourse().getName();
            String gradeLetter = cg.getGrade() != null ? cg.getGrade() : "N/A";

            long submissionCount = student.getSubmissions().stream()
                    .filter(as -> as.IsSubmissionThisCourseAssignment(cg.getCourse()))
                    .count();

            int totalAssignments = cg.getCourse().getCourseWorkNum(); 
            double progress = totalAssignments > 0 ? ((double) submissionCount / totalAssignments) * 100 : 0;

            if (cg.getGrade() != null && !cg.getGrade().equalsIgnoreCase("F") && submissionCount >= 10) {
                earnedCredits += cg.getCourse().getCredits();

                if ("INFO 5100".equalsIgnoreCase(courseId)) {
                    hasCore = true;
                }
            }

            // 构建成绩单文本
            transcriptText.append(String.format("%s - %s | Grade: %s | Submitted: %d/%d (%.0f%%)%n",
                    courseId, courseName, gradeLetter, submissionCount, totalAssignments, progress));
        }
        
        double overallGPA = student.calculateOverallGPA();

        boolean ready = earnedCredits >= 32 && hasCore && overallGPA >= 3.0;

        lblTotalCredits.setText(earnedCredits + " / 32 credits");
        lblComplete.setText(hasCore ? "✅ Completed" : "❌ Not Completed");
        lblGPA.setText(String.format("%.2f", overallGPA));
        lblStatus.setText(ready ? "🎓 READY TO GRADUATE!" : "📘 IN PROGRESS – Requirements not yet met");
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this,
            "❌ Error performing graduation audit: " + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
}  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();
        lblTotalCredits = new javax.swing.JLabel();
        lblStudentID1 = new javax.swing.JLabel();
        lblComplete = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblGPA = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Graduation Audit");

        lblUserName.setText("Graduation Status:");

        lblStudentID.setText("Total Earned Credits:");

        lblTotalCredits.setText("0/32 credits");

        lblStudentID1.setText("Core Course(INFO 5100):");

        lblComplete.setText("Completed");

        jLabel2.setText("GPA:");

        lblGPA.setText("0.00");

        lblStatus.setText("In progress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStudentID1)
                            .addComponent(jLabel2)
                            .addComponent(lblStudentID))
                        .addGap(86, 86, 86)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(lblGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentID)
                    .addComponent(lblTotalCredits))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentID1)
                    .addComponent(lblComplete))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblGPA))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblComplete;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentID1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCredits;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
