/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import Business.UserAccounts.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    UserAccount useraccount;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public FacultyWorkAreaJPanel(Business b, JPanel clp, UserAccount ua) {

        business = b;
        this.CardSequencePanel = clp;
        useraccount = ua;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCourse = new javax.swing.JButton();
        btnManageStudentProfiles = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnPerfomanceReports = new javax.swing.JButton();
        lblTitile = new javax.swing.JLabel();

        setForeground(new java.awt.Color(51, 51, 51));

        btnManageCourse.setBackground(new java.awt.Color(102, 153, 255));
        btnManageCourse.setFont(getFont());
        btnManageCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourse.setText(" Manage Courses");
        btnManageCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCourse.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageCourse.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageCourse.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageStudentProfiles.setBackground(new java.awt.Color(102, 153, 255));
        btnManageStudentProfiles.setFont(getFont());
        btnManageStudentProfiles.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStudentProfiles.setText("Manage Students");
        btnManageStudentProfiles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudentProfiles.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudentProfiles.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudentProfiles.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudentProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentProfilesActionPerformed(evt);
            }
        });

        btnMyProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnMyProfile.setFont(getFont());
        btnMyProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProfile.setText("My Profile");
        btnMyProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnMyProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMyProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerfomanceReports.setBackground(new java.awt.Color(102, 153, 255));
        btnPerfomanceReports.setFont(getFont());
        btnPerfomanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfomanceReports.setText("Performance Reports");
        btnPerfomanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerfomanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerfomanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerfomanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerfomanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfomanceReportsActionPerformed(evt);
            }
        });

        lblTitile.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitile.setText("My Faculty Profie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(btnManageStudentProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerfomanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitile, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitile)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudentProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfomanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCourseIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();
        ManageCourseJPanel mc = new ManageCourseJPanel(business, CardSequencePanel,useraccount);

        CardSequencePanel.add("Manage Course", mc);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageCourseIdentifyResourceAssetsActionPerformed

    private void btnManageStudentProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentProfilesActionPerformed
        // TODO add your handling code here:
        StudentManagementJPanel sm = new StudentManagementJPanel(business, CardSequencePanel,useraccount);

        CardSequencePanel.add("Manage Student", sm);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageStudentProfilesActionPerformed

    private void btnMyProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileIdentifyEventsActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();
        //    IdentifyEventTypes iet= new IdentifyEventTypes(businessunit, CardSequencePanel);

        //    CardSequencePanel.add("IdentifyEventTypes", iet);
        ManageFacultyProfilesJPanel mfp = new ManageFacultyProfilesJPanel(business, CardSequencePanel, useraccount);
        CardSequencePanel.add("ManageFacultyProfiles", mfp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
}//GEN-LAST:event_btnMyProfileIdentifyEventsActionPerformed

    private void btnPerfomanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfomanceReportsActionPerformed
        // TODO add your handling code here:
        PerformanceReportJPanel pr = new PerformanceReportJPanel(business, CardSequencePanel, useraccount);
        CardSequencePanel.add("Performance Report", pr);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnPerfomanceReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourse;
    private javax.swing.JButton btnManageStudentProfiles;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnPerfomanceReports;
    private javax.swing.JLabel lblTitile;
    // End of variables declaration//GEN-END:variables

}
